name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le projet
        uses: actions/checkout@v5

      - name: Installer Java 24
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '24'

      - name: Donner les permissions à Gradle
        working-directory: projet_android
        run: chmod +x ./gradlew

      - name: Construire l'APK
        working-directory: projet_android
        run: ./gradlew assembleDebug

      - name: Publier l'APK
        uses: actions/upload-artifact@v5
        with:
          name: CrashAnalyzer-debug
          path: projet_android/app/build/outputs/apk/debug/*.apk
